#-------------------------------
# General Site Settings
title: Jimmyberg's Dev blog
logo:  # You can add own logo.
description: The NEW Jimmyberg's blog.


#-------------------------------
# Author Settings
author:
  name: Ji Yoon Kim
  image: profile.jpg
  say-hello: <strong>사막을 건너는 낙타처럼..</strong>
  bio: 무더운 사막을 묵묵히 한 발자국씩 나아가는 낙타처럼, 꾸준히 배우고 성장하여, 보다 더 멋지고, 성숙한 Back-End 개발자가 되기 위한 기록 저장소.<br><strong>#Back-End,#Java,#SpringFramework,#JPA,#Oracle,#Kotlin</strong>


#-------------------------------
# Contact links
facebook: https://www.facebook.com/kim90314
instagram: https://www.instagram.com/_jimmyberg_
github: https://github.com/JiYoonKimjimmy


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: _jimmyberg_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
